### ISSUE TITLE
"Uncaught error in invocation... Converting circular structure to JSON" 

### ISSUE THREAD

**Issue by andyperlitch** [tjworks/angoose#32]
Hi @tjworks,

I am getting a "Converting circular structure to JSON" error (full log entry below). It seems to be related to [this code snippet in Pipeline.js](https://github.com/tjworks/angoose/blob/master/lib/Pipeline.js#L309-L311), and I am curious why [this commit](https://github.com/tjworks/angoose/commit/32fb2c33e99bad1f23dc855f5978a4c4a110f4d9) looks as if you were trying to improve this situation but I am still running into it.

I am attempting to use this with mongoose v4.0.6 despite your warnings so perhaps it is related to the version of mongoose, but based on the changelog from v3 to v4 it didn't look like much would actually be affected.

Thanks in advance,
Andy

```
[2015-10-08 18:22:41.391] [ERROR] angoose - Uncaught error in invocation #40010000 { [TypeError: Converting circular structure to JSON]
  domain: 
   { domain: null,
     _events: { error: [Function: uncaught] },
     _maxListeners: undefined,
     members: [],
     context: 
      { seqnum: 40010000,
        request: [Object],
        response: [Object],
        getRequest: [Function],
        getResponse: [Function],
        getInvocation: [Function],
        setUser: [Function],
        getUser: [Function],
        setPrincipal: [Function],
        getPrincipal: [Function],
        toString: [Function],
        invocation: [Object] } },
  domainThrown: true }
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.json (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/express/lib/response.js:242:19)
    at ServerResponse.send (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/express/lib/response.js:151:21)
    at /Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/lib/Pipeline.js:312:13
    at Pipeline.<anonymous> (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/lib/Pipeline.js:277:41)
    at next_ (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/node_modules/hooks/hooks.js:77:34)
    at fnWrapper (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/node_modules/hooks/hooks.js:172:15)
    at Pipeline.postPack (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/extensions/angoose-mongoose.js:167:5)
    at next_ (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/node_modules/hooks/hooks.js:74:35)
    at fnWrapper (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/node_modules/hooks/hooks.js:172:15)
    at Pipeline.pack (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/lib/Pipeline.js:147:5)
    at Pipeline._done (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/node_modules/hooks/hooks.js:89:24)
    at Pipeline._next (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/node_modules/hooks/hooks.js:52:28)
    at Pipeline.proto.(anonymous function) [as pack] (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/node_modules/hooks/hooks.js:109:20)
    at Pipeline.<anonymous> (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/lib/Pipeline.js:274:46)
    at next_ (/Users/andyperlitch/Sites/andyperlitch.net/v2/node_modules/angoose/node_modules/hooks/hooks.js:77:34)
```

**Comment by devmsh** [comment]
@andyperlitch do you find any replacement?
